### ISSUE TITLE
fdk-aac in in Platform/Sdk

### ISSUE THREAD

**Issue by Erick555** [flathub/org.videolan.VLC.Plugin.fdkaac#4]
For some time fdk-aac should be available in Platform/Sdk for kde 5.12/5.13 so I guess config switch may be added to vlc app and extension removed.

@MatMaul

**Comment by MatMaul** [comment]
Unfortunately the problem here is incompatibility of licenses. FDK AAC has some clause that make it incompatible with GPL. The core of VLC and lot of its plugins are LGPL (including the fdkaac one), however the whole VLC is GPL.
I would be happy to put it back in the main VLC if this situation changed but I don't think it's the case.

**Comment by Erick555** [comment]
@MatMaul Hm, ok. FYI runtime ships special version sometimes called [fdk-aac-free](https://cgit.freedesktop.org/~wtay/fdk-aac/tree/?h=stripped4) which make it eligible to ship by distros like fedora without patent restrtiction. I don't know if it make it compatible with gpl though.
